
name: Windows Build
on:
  push:
jobs:
  build:
    name: Windows Build
    permissions: write-all
    runs-on: windows-latest
    steps:
      - name: Pulling the new commit
        uses: actions/checkout@v4.1.7
      - name: Setting up Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.5
      - name: Restore existing build cache for faster compilation
        uses: actions/cache@v4.0.2
        with:
          # not caching the bin folder to prevent asset duplication and stuff like that
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
      - name: Installing/Updating libraries
        run: |
          haxe -cp setup -D analyzer-optimize -main Main --interp
        shell: cmd
      - name: Building the game
        run: |
          haxelib run lime build windows

      - name: Uploading artifact (entire build)
        uses: actions/upload-artifact@v4.3.4
        with:
          name: SC-SP-Engine
          path: export/release/windows/bin
      - name: Clearing already existing cache
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches) {
              if (cache.key == "cache-build-windows") {
                console.log('Clearing ' + cache.key + '...')
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })
                console.log("Cache cleared.")
              }
            }
      - name: Uploading new cache
        uses: actions/cache@v4.0.2
        with:
          # caching again since for some reason it doesnt work with the first post cache shit
          key: cache-build-windows
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          restore-keys: |
            cache-build-windows
